CREATE TABLE IF NOT EXISTS users (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    username     VARCHAR(50)  NOT NULL UNIQUE,
    email        VARCHAR(120) DEFAULT NULL,
    password_hash VARCHAR(255) NOT NULL,
    balance      DECIMAL(8,2) NOT NULL DEFAULT 0.00,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);